### ISSUE TITLE
Broke ST2 Compatibility

### ISSUE THREAD

**Issue by jsadeli** [danro/refined-theme#2]
Hi @danro, I've been using your `Refined-Light` theme for a long time instead of `Soda Light` since it's, well, more refined :)

However, it seems that the latest update/commit broke the theme on ST2 build 2217 (stable - v2.0.1). Tried the latest theme update on a clean ST2 install and it still has the same issue.

![before](https://f.cloud.github.com/assets/627874/345148/7a7d2124-9e18-11e2-8f98-171eddb46727.png)
![after](https://f.cloud.github.com/assets/627874/345149/7c8891f6-9e18-11e2-9edd-e37dac6de181.png)

**Comment by danro** [comment]
@jsadeli Thanks, should be fixed now.. let me know if it's still not working.
